name: CI/CD - Build and Push to Docker Hub

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build the Spring Boot JAR
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-cicd-demo:latest .

      # 6️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-cicd-demo:latest
